### ISSUE TITLE
Incompatible BlockToeplitz constructor

### ISSUE THREAD

**Issue by aytekinar** [neveritt/GeneralizedSchurAlgorithm.jl#5]
### Description

We have a `v0.5` feature which needs attention. Currently, `BlockToeplitz` type is not `v0.4` compatible.
### Desired Behaviour

Line 30 of `src/blocktoeplitz.jl` in c8143f0 should have been

``` julia
@compat function (::Type{BlockToeplitz}){M1,M2}(vc::M1, vr::M2)
  @assert eltype(M1) == eltype(M2) "Col and row must have same eltype"
  k = size(vr,1)
  l = size(vc,2)
  if !isapprox(vc[1:k,1:l], vr[1:k,1:l])
    warn("First block element must be the same")
    throw(DomainError())
  end
  T = promote_type(eltype(M1), eltype(M2), Float32)
  new{T,M1,M2}(vc,vr)
end
```
### Observed Behaviour

The _lack_ of `@compat` above.
### Notes

Blocking KTH-AC/IdentificationToolbox.jl#1.

**Comment by neveritt** [comment]
Closed with 49aec99
